server:
  port: 8080

spring:
  application:
    name: customer-service
  datasource:
    username: 'aelatrouz'
    url: jdbc:postgresql://localhost:5432/customer
    password: 'password'
  jpa:
    show-sql: 'true'
    generate-ddl: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update

